version: '3.8'

services:
  azure-devops-agent:
    image: test-azure-agent:latest
    # image: hypolas/azure-devops-agent:latest
    container_name: azure-agent-test
    hostname: azure-agent-test
    restart: unless-stopped
    
    # Environment variables to test the image
    environment:
      # Azure DevOps configuration (REQUIRED for actual testing)
      # ⚠️ Replace these values with your actual values
      - AZP_URL=${AZP_URL}
      - AZP_TOKEN=${AZP_TOKEN}
      - AZP_POOL=${AZP_POOL}
      - AZP_AGENT_NAME=test-${HOSTNAME:-local}
      - AGENT_NUMBER=1
      - INSTANCE_ID=i-1234567890abcdef0
      - INSTALL_FOLDER=${INSTALL_FOLDER}

      # AWS configuration (OPTIONAL - to retrieve token from AWS Secrets Manager)
      # If using AWS Secrets Manager instead of direct AZP_TOKEN:
      # - AWS_REGION=eu-west-1
      # - AZURE_DEVOPS_TOKEN_SECRET_ARN=arn:aws:secretsmanager:eu-west-1:account:secret:azure-devops-token

      # EC2 configuration (OPTIONAL - for automatic names)
      # - INSTANCE_ID=i-1234567890abcdef0

      # Docker-in-Docker configuration
      - DEFAULT_CONTAINER_IMAGE=ubuntu:22.04
      - DEFAULT_VOLUMES=/var/run/docker.sock:/var/run/docker.sock,/cache:/cache,/data:/data

    # Required volumes
    volumes:
      # Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${INSTALL_FOLDER}:${INSTALL_FOLDER}

    # Isolated network for testing
    networks:
      - azure-agent-test-network

    # Healthcheck to verify agent is running
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'Agent.Listener' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

    # Resource limits for testing
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  azure-agent-test-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16