version: '3.8'

services:
  azure-agent:
    build:
      context: .
      args:
        # aws-ssm installé par défaut (hypolas/aws-ssm-light)
        INSTALL_AWS_SSM: "true"
    
    container_name: azure-devops-agent
    hostname: azure-agent
    
    environment:
      # Configuration Azure DevOps (obligatoire)
      - AZP_URL=${AZP_URL}
      - AZP_POOL=${AZP_POOL}
      - AZP_AGENT_NAME=${AZP_AGENT_NAME:-azure-agent}
      - AGENT_NUMBER=${AGENT_NUMBER:-1}
      
      # AWS pour récupération du token (si pas AZP_TOKEN fourni)
      - AWS_REGION=${AWS_REGION}
      - AZURE_DEVOPS_TOKEN_SECRET_ARN=${AZURE_DEVOPS_TOKEN_SECRET_ARN}
      
      # Token direct (optionnel, prioritaire sur AWS)
      - AZP_TOKEN=${AZP_TOKEN}
      
      # Configuration conteneur
      - DEFAULT_CONTAINER_IMAGE=ubuntu:22.04
      - DEFAULT_VOLUMES=/var/run/docker.sock:/var/run/docker.sock,/cache:/cache,/data:/data
    
    volumes:
      # Socket Docker pour builds
      - /var/run/docker.sock:/var/run/docker.sock
      # Cache persistant
      - ./cache:/cache
      - ./data:/data
    
    restart: unless-stopped
    
    # Healthcheck pour vérifier que l'agent fonctionne
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'Agent.Listener' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Volumes nommés pour persistance
volumes:
  agent-cache:
    driver: local
  agent-data:
    driver: local